### ISSUE TITLE
Feature Request: Show Subscription IDs as well

### ISSUE THREAD

**Issue by vikas027** [riweston/aztx#18]
Thanks for creating this nifty tool.

It will also be good to show subscription IDs when running `aztx` command. Something like this:

```bash
sub1 (xxxxx)
sub2 (yyyy)
```

**Comment by riweston** [comment]
An update on this request, I've roughly implemented a columnar style display output with fzf and I just need to write up some tests before release. This is the kind of thing the you're looking for, correct?

![image](https://github.com/riweston/aztx/assets/22933083/cb4c950c-8243-4577-9d63-40417a680260)

You can filter using the ID too with this displayed in the fzf output

**Comment by vikas027** [comment]
This is so good. Thanks @riweston .

**Comment by riweston** [comment]
Released in version [`1.0.1`](https://github.com/riweston/aztx/releases/tag/1.0.1) 😄
