### ISSUE TITLE
Feature Request - Switch easily to the last subscription

### ISSUE THREAD

**Issue by vikas027** [riweston/aztx#19]
It will be good to have a feature where someone can run `aztx -` (something like `cd -`) and switch the previous subscription.

**Comment by riweston** [comment]
Update on this request, this is roughly implemented and I'm just going to add some tests to my code as a next step before release

![image](https://github.com/riweston/aztx/assets/22933083/92be4b35-bc45-4834-a6ad-f0a2ff90ac33)

**Comment by riweston** [comment]
Released in version [`1.0.1`](https://github.com/riweston/aztx/releases/tag/1.0.1) 😄
